version: '3'
services:
  web:
    image: "sample-app:1.0"
    command: start
    volumes:
      - /opt/docker-vols/sample-app:/app
    networks:
    #  - intranet  
      - locallan
    restart: "on-failure:3"
    ulimits:    
      nofile:
        soft: 4000
        hard: 8000 
networks:
  intranet:
    external:
      name: vlan254
  locallan:
    external:
      name: vlanbridge
