version: '3.3'
services:
  web:
    image: "sample-app:1.0"
    command: start
    volumes:
      - type: volume
        source: sample-app
        target: /app
        read_only: false
    networks:
      - locallan
    restart: "unless-stopped"
    ulimits:    
      nofile:
        soft: 4000
        hard: 8000 
networks:
  intranet:
    external:
      name: vlan254
  locallan:
    external:
      name: vlanbridge
volumes:
  sample-app:
    external: true    
